### ISSUE TITLE
Bug no botão dos Comentário | Estado (...)

### ISSUE THREAD

**Issue by Nardoiri** [innercoders/tether#1]
Na página de um post, não consigo clicar nesses botões pois fica **piscando** toda hora quando passo o cursor em cima.

![bug_botao](https://cloud.githubusercontent.com/assets/22132664/18418296/6a548ae2-7819-11e6-9927-ab675daed9f6.jpg)

**Comment by feliperodrigues** [comment]
O erro está acontecendo quando o ToolBar do Wordpress está ativo. Ainda não sei qual a causa do problema, mas vou deixar desabilitado.

Isso deve corrigir o problema por agora.

**Comment by Nardoiri** [comment]
Tudo certo, valeu!

**Comment by feliperodrigues** [comment]
Ficou decidido remover a admin toolbar wordpress, até para não induzir o usuário a ir em páginas erradas.

Outra toolbar foi adicionada, feita no próprio Salient.
