### ISSUE TITLE
Botão da tela inicial do Q&A

### ISSUE THREAD

**Issue by Nardoiri** [innercoders/tether#2]
Gostaria que tivesse um botão para voltar na página inicial do Q&A enquanto eu estou no meio de um post.

**Comment by feliperodrigues** [comment]
Eu adicionei alguns botões para facilitar a Navegação.

No topo eu inseri o menu **Tether > Perguntas e Respostas | Perguntar** e no topo de todas as páginas do Q&A eu adicionei o caminho de migalhas ( *Breadcrumbs* ).
