### ISSUE TITLE
Problema para anexar numa resposta de post

### ISSUE THREAD

**Issue by Nardoiri** [innercoders/tether#3]
Por algum motivo, eu não consigo anexar uma imagem para responder um post (eu insiro a imagem, mas não aparece nada), e gostaria que tivesse também uma aba de preview da minha resposta também.

**Comment by feliperodrigues** [comment]
A configuração do Upload estava com 0.1mb, alterei pra 2mb.

Aparece uma mensagem de erro na parte inferior esquerda do site, mas apenas na primeira vez que tenta.

Deve estar funcionando parcialmente agora.

**Comment by feliperodrigues** [comment]
O problema do editor foi corrigido no último hotfix.

Agora está usando o tinymce corretamente, permitindo a pre-visualização do post.
